#!/usr/bin/env python3
# addons/stackgres/disable

import os
import subprocess

import click

HELM = '/snap/bin/microk8s.helm3'
AD_NAME = 'stackgres-k8s'


@click.command()
def main():
    click.echo(f'Disabling {AD_NAME}')

    # uninstall stackgres-operator
    subprocess.check_call([
        HELM, 'uninstall',
        '--namespace', 'stackgres',
        'stackgres-operator'
    ])

    # uninstall moniroting
    subprocess.check_call([
        HELM, 'uninstall',
        '--namespace', 'monitoring',
        'prometheus-operator',
    ])

    click.echo(f'Disabled {AD_NAME}')


if __name__ == '__main__':
    main()
