#!/usr/bin/env python3
# addons/stackgres/enable

import subprocess

import click

HELM = '/snap/bin/microk8s.helm3'
ENABLE = '/snap/bin/microk8s.enable'
STATUS = '/snap/bin/microk8s.status'
AD_NAME = 'stackgres-k8s'
CHART_VERSION = '1.4.3'

MONITORING_OPTIONS = [
    '--set', 'grafana.autoEmbed=true',
    '--set-string', 'grafana.webHost=prometheus-operator-grafana.monitoring',
    '--set-string', 'grafana.secretNamespace=monitoring',
    '--set-string', 'grafana.secretName=prometheus-operator-grafana',
    '--set-string', 'grafana.secretUserKey=admin-user',
    '--set-string', 'grafana.secretPasswordKey=admin-password',
]


def check_if_prometheus_enabled():
    check_prometheus_cmd = [
        STATUS, '-a', 'prometheus-k8s'
    ]
    return subprocess.check_output(
        check_prometheus_cmd,
    ).decode() == 'enabled'


cmd = [
        HELM, 'install',
        '--create-namespace', '--namespace', 'stackgres',
        'stackgres-operator',
        '--version', CHART_VERSION,
        'stackgres-charts/stackgres-operator',
        '--set-string', 'adminui.service.type=ClusterIP'
]


@click.command()
def main():
    global cmd
    click.echo(f'Enabling {AD_NAME}')

    # enable dependencies
    dependecies = ['dns', 'helm3']
    for dependency in dependecies:
        subprocess.check_call([ENABLE, dependency])

    if check_if_prometheus_enabled():
        cmd = cmd.extend(MONITORING_OPTIONS)
        click.echo('Enabling prometheus')
        # enable prometheus
        subprocess.check_call([
           ENABLE, 'prometheus-k8s'
        ])

    # add stackgres helm repo
    subprocess.check_call([
        HELM, 'repo', 'add', 'stackgres-charts',
        'https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/'
    ])

    # update repo
    subprocess.check_call([
        HELM, 'repo', 'update'
    ])

    # install chart
    subprocess.check_call(cmd)
    click.echo(f'Enabled {AD_NAME}')


if __name__ == '__main__':
    main()
