#!/usr/bin/env python3
# addons/stackgres/enable

import os
import subprocess

import click

HELM = '/snap/bin/microk8s.helm3'
ENABLE = '/snap/bin/microk8s.enable'
AD_NAME = 'stackgres-k8s'
CHART_VERSION = '1.4.3'


@click.command()
def main():
    click.echo(f'Enabling {AD_NAME}')

    # enable dns
    subprocess.check_call([
        ENABLE, 'dns'
    ])

    # add prometheus helm repo
    subprocess.check_call([
        HELM, 'repo', 'add',
        'prometheus-community',
        'https://prometheus-community.github.io/helm-charts'
    ])

    # install prometheus
    subprocess.check_call([
        HELM, 'install',
        '--create-namespace', '--namespace',
        'monitoring', 'prometheus-operator',
        'prometheus-community/kube-prometheus-stack'
    ])

    # add stackgres helm repo
    subprocess.check_call([
        HELM, 'repo', 'add', 'stackgres-charts',
        'https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/'
    ])

    # update repo
    subprocess.check_call([
        HELM, 'repo', 'update'
    ])

    # install chart
    subprocess.check_call([
        HELM, 'install',
        '--create-namespace', '--namespace', 'stackgres',
        'stackgres-operator',
        '--set', 'grafana.autoEmbed=true',
        '--set-string', 'grafana.webHost=prometheus-operator-grafana.monitoring',
        '--set-string', 'grafana.secretNamespace=monitoring',
        '--set-string', 'grafana.secretName=prometheus-operator-grafana',
        '--set-string', 'grafana.secretUserKey=admin-user',
        '--set-string', 'grafana.secretPasswordKey=admin-password',
        '--set-string', 'adminui.service.type=ClusterIP',
        '--version', CHART_VERSION,
        'stackgres-charts/stackgres-operator'
    ])

    click.echo(f'Enabled {AD_NAME}')


if __name__ == '__main__':
    main()
