#!/usr/bin/env python3
import subprocess
import click

AD_NAME = 'prometheus-k8s'
HELM = '/snap/bin/microk8s.helm3'
ENABLE = '/snap/bin/microk8s.enable'


def main():
    click.echo(f'Disabling {AD_NAME}')

    # uninstall prometheus
    subprocess.check_call([
        HELM, 'uninstall',
        '--namespace', 'monitoring',
        'prometheus-operator',
    ])

    click.echo(f'Disabled {AD_NAME}')


if __name__ == '__main__':
    main()
