#!/usr/bin/env python3
# addons/n8n/enable

import subprocess
import click
from secrets import token_urlsafe
from base64 import b64encode

HELM = '/snap/bin/microk8s.helm3'
ENABLE = '/snap/bin/microk8s.enable'
AD_NAME = 'n8n-k8s'
CHART_VERSION = '0.10.0'


@click.command()
def main():
    click.echo(f'Enabling {AD_NAME}')

    # enable dns
    subprocess.check_call([
        ENABLE, 'dns'
    ])

    # add helm repo
    subprocess.check_call([
        HELM, 'repo', 'add', 'open-8gears-mod', 'https://get-zen-dev.github.io/n8n-helm-chart/'
    ])

    # install
    subprocess.check_call([
        HELM, 'install', 'n8n', 'open-8gears-mod/n8n',
        '--create-namespace', '--namespace', 'n8n',
        '--version', CHART_VERSION
    ])

    click.echo(f'Enabled {AD_NAME}')


if __name__ == '__main__':
    main()
