#!/usr/bin/env python3
# addons/appsmith/disable

import os
import subprocess

import click

HELM = '/snap/bin/microk8s.helm3'
AD_NAME = 'appsmith-k8s'

    
def main():
    click.echo(f'Disabling {AD_NAME}')
    subprocess.check_call([
        HELM, 'uninstall', 'appsmith',
    ])
    click.echo(f'Disabled {AD_NAME}')


if __name__ == '__main__':
    main()
