#!/usr/bin/env python3
# addons/appsmith/enable

import os
import subprocess

import click

HELM = '/snap/bin/microk8s.helm3'
AD_NAME = 'appsmith-k8s'
CHART_VERSION = '2.0.0'
ARGS_PATH = f'/var/snap/microk8s/current/args/{AD_NAME}'


@click.command()
@click.option('--namespace', required=False, default='default', type=str)
def main(namespace):
    click.echo(f'Enabling {AD_NAME}')

    subprocess.check_call([
        'mkdir', '-p', ARGS_PATH
    ])

    # download values.yaml
    subprocess.check_call([
        'curl', '-L', 'https://bit.ly/3ETEgPT', '-o', f'{ARGS_PATH}/values.yaml'
    ])

    # add helm repo
    subprocess.check_call([
        HELM, 'repo', 'add', 'appsmith', 'https://helm.appsmith.com'
    ])

    # install
    subprocess.check_call([
        HELM, 'install', 'appsmith', 'appsmith/appsmith',
        '--namespace', namespace,
        '--version', CHART_VERSION
    ])

    click.echo(f'Enabled {AD_NAME}')


if __name__ == '__main__':
    main()
